### ISSUE TITLE
Monitoring and Observability

### ISSUE THREAD

**Issue by gorkem** [janus-idp/backstage-showcase#229]
## Goal
Enable reporting on the overall health of the portal. Provide monitoring for crucial system metrics. Introduce tooling to help understand and debug issues in production. Enable data that help trace, understand, and diagnose problems in production environments.

Some of the areas of work are 

- Metrics (Prometheus) 
- Logging
- Health Checks
- (Distributed) Tracing (moved to separate epic https://github.com/janus-idp/backstage-showcase/issues/632)

## Acceptance criteria

- [x] Users can enable their Backstage instance to output metrics in a format that can be pulled in by Prometheus.
- [x] User can enable structured logging and can send them to log repositories 
- [x] Health Checks for the backstage instance is available
- [ ] Users can optionally enable Tracing (moved to separated epic https://github.com/janus-idp/backstage-showcase/issues/632)
- [x] Documentation is available 

## Requirements

- [ ] Plugin
- [ ] Test plan
- [x] Installation documentation
- [x] End user documentation

## Issues in Epic

- [x] #230
- [x] #500 
- [x] #565
- Users can optionally enable Tracing
  - [x] #582

## Notes

**Additional context**

**Comment by kadel** [comment]
A few notes from the discussion with Christophe:
- The important part is monitoring. Ideally, it should integrate with [OpenShift monitoring](https://docs.openshift.com/container-platform/4.13/monitoring/monitoring-overview.html), but users should also be able to use their own Prometheus instance.
- If there is no time, tracing and logging can wait after Milestone 4
- Similarly to monitoring tracing should integrate with [OpenShift tracing](https://docs.openshift.com/container-platform/4.13/distr_tracing/distr_tracing_arch/distr-tracing-architecture.html) (Jeager and OpenTelemetry)
- Logging should also integrate with [OpenShift logging](https://docs.openshift.com/container-platform/4.13/logging/cluster-logging.html).

**Comment by rtaniwa** [comment]
@kadel assuming the spike is complete, is this epic now complete (all acceptance criteria met)? Do we have documentation that the doc team can use to seed their content?

**Comment by kadel** [comment]
> @kadel assuming the spike is complete, is this epic now complete (all acceptance criteria met)? Do we have documentation that the doc team can use to seed their content?

Except for the tracing all acceptance criteria a met. Upstream documentation is in Getting started guide (https://github.com/janus-idp/backstage-showcase/blob/main/showcase-docs/getting-started.md)

I kept this open to remind myself that I needed to create a new epic to capture the tracing part, which we will do later.

**Comment by kadel** [comment]
I've created a separate epic (https://github.com/janus-idp/backstage-showcase/issues/632) for tracking Tracing related work, which we will do later.
