### ISSUE TITLE
UI: Support Dark, Light & Auto themes

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-showcase#344]
## Goal
_Details to follow_

### What problem does this solve?
_Details to follow_
 
### Acceptance criteria
_Details to follow_

## Requirements
- [ ] Feature
- [ ] Test plan
- [ ] Installation documentation
- [ ] End user documentation

## Issues in Epic
- [x] https://github.com/janus-idp/backstage-showcase/issues/499
- [x] https://github.com/janus-idp/backstage-showcase/issues/379
- [x] https://github.com/janus-idp/backstage-showcase/issues/513
- [x] https://github.com/janus-idp/backstage-showcase/issues/540
- [x] https://github.com/janus-idp/backstage-showcase/issues/531
- [x] https://github.com/janus-idp/backstage-showcase/issues/530

**Comment by divyanshiGupta** [comment]
@jasperchui I have created this story - https://github.com/janus-idp/backstage-showcase/issues/499 for this epic but dont see an option to edit the description for this ticket so can you add this in the issues section or provide access to edit?

**Comment by divyanshiGupta** [comment]
Story for adding dark theme in showcase - https://github.com/janus-idp/backstage-showcase/issues/513

cc: @invincibleJai

**Comment by invincibleJai** [comment]
> Story for adding dark theme in showcase - #513
> 
> cc: @invincibleJai

I have linked the issue in the epic , and I think we can as well close https://github.com/janus-idp/backstage-showcase/issues/379 ? can you close it with a comment?

**Comment by divyanshiGupta** [comment]
> > Story for adding dark theme in showcase - #513
> > cc: @invincibleJai
> 
> I have linked the issue in the epic , and I think we can as well close #379 ? can you close it with a comment?
> 
> and shall we create a ticket for QE/Docs for this as well as needed

@invincibleJai can you also link https://github.com/janus-idp/backstage-showcase/issues/499 as this is also a part of this epic? Sure will close #379.

Will create tickets for QE/Docs.

**Comment by divyanshiGupta** [comment]
> > > Story for adding dark theme in showcase - #513
> > > cc: @invincibleJai
> > 
> > 
> > I have linked the issue in the epic , and I think we can as well close #379 ? can you close it with a comment?
> > and shall we create a ticket for QE/Docs for this as well as needed
> 
> @invincibleJai can you also link #499 as this is also a part of this epic? Sure will close #379.
> 
> Will create tickets for QE/Docs.

QE/Docs tickets:

- https://github.com/janus-idp/backstage-showcase/issues/531
- https://github.com/janus-idp/backstage-showcase/issues/530

Also have closed - #379.

**Comment by invincibleJai** [comment]
> > > > Story for adding dark theme in showcase - #513
> > > > cc: @invincibleJai
> > > 
> > > 
> > > I have linked the issue in the epic , and I think we can as well close #379 ? can you close it with a comment?
> > > and shall we create a ticket for QE/Docs for this as well as needed
> > 
> > 
> > @invincibleJai can you also link #499 as this is also a part of this epic? Sure will close #379.
> > Will create tickets for QE/Docs.
> 
> QE/Docs tickets:
> 
> * [QE for themes #531](https://github.com/janus-idp/backstage-showcase/issues/531)
> * [Documentation for showcase themes #530](https://github.com/janus-idp/backstage-showcase/issues/530)
> 
> Also have closed - #379.

Done, have linked those and have linked https://github.com/janus-idp/backstage-showcase/issues/540 as well

**Comment by jasperchui** [comment]
Closing as engineering tasks are completed.
