### ISSUE TITLE
UI updates due to UX Review

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-showcase#368]
## Goal
The UX team will be performing a UX review around recommendations regarding the following:
- Design conventions to be used in plugins
- Guidelines around side navigation (sections for nav items, flyout versus accordion when using 2ndary nav items, etc)
- Terminology consistency
- Should K8S plugin be shown as a tab in entity.yaml or high level and combined with Multi cluster/ROSA plugins

## Acceptance criteria
- [ ] tdb

## Requirements

- [ ] Plugin
- [ ] Test plan
- [ ] Installation documentation
- [ ] End user documentation

## Issues in Epic

- [x] https://github.com/janus-idp/backstage-plugins/issues/804
- [x]  https://github.com/RoadieHQ/roadie-backstage-plugins/issues/1150

## Notes

**Additional context**

**Comment by invincibleJai** [comment]
Closing it as tickets linked here are closed, for further enhancement we'll open a separate ticket
