### ISSUE TITLE
Dynamic plugin support

### ISSUE THREAD

**Issue by serenamarie125** [janus-idp/backstage-showcase#442]
The problem
Currently users are forced to rebuild/redeploy after adding a new Backstage plugin

## Sub-Tasks

- [x] First POC of dynamic frontend plugins: [POC of basic scalprum integration](https://github.com/janus-idp/backstage-scalprum/commit/c9419223f6d03f0d080d588430290d960cb2c190)
- [x] First RFC about dynamic frontend plugins: https://github.com/backstage/backstage/issues/17054
- [x] POC of dynamic backend plugins: https://github.com/backstage/backstage/compare/master...davidfestal:backstage:backend-dynamic-plugins
- [x] RFC of dynamic backend plugins: https://github.com/backstage/backstage/issues/18390
- [x] Experimental MVP implementation of dynamic backend plugin support in upstream
  - [x] https://github.com/janus-idp/book/issues/18
  - [x] https://github.com/janus-idp/backstage-showcase/issues/444
- [x] Add dynamic backend plugin support to the Janus Showcase
  - [x] https://github.com/janus-idp/backstage-showcase/issues/526
  - [x] https://github.com/janus-idp/backstage-plugins/issues/727
  - [x] https://github.com/janus-idp/helm-backstage/issues/118
  - [x] https://github.com/janus-idp/backstage-showcase/issues/528
  - [x] https://github.com/janus-idp/backstage-showcase/issues/627
  - [x] https://github.com/janus-idp/backstage-showcase/issues/641
- [x] final attempt at dynamic frontend  plugins
  - [x] New frontend POC / RFC compatible with the declarative-integration
  - [x] https://github.com/janus-idp/backstage-plugins/issues/726
  - [x] https://github.com/janus-idp/backstage-showcase/issues/583
  - [x] final implementation of frontend changes in Janus showcase
    - [x] finishing implementation (https://github.com/janus-idp/backstage-showcase/pull/659)
    - [x] removing static frontend plugins
    - [x] adding dynamic frontend plugins and configuration ( https://github.com/janus-idp/backstage-showcase/pull/683 https://github.com/janus-idp/backstage-showcase/pull/699)
    - [x] final integration/polishing
- [x] Robustness
  - [x] https://github.com/janus-idp/backstage-showcase/issues/527
  - [x] https://github.com/janus-idp/backstage-showcase/issues/727
  - [x] https://github.com/janus-idp/backstage-showcase/issues/725
  - [x] https://github.com/janus-idp/backstage-showcase/issues/724
  - [x] https://github.com/janus-idp/backstage-showcase/issues/726
