### ISSUE TITLE
Localization (placeholder)

### ISSUE THREAD

**Issue by rtaniwa** [janus-idp/backstage-showcase#502]
## Goal
This epic covers investigating how to make use of the upstream i18n implementation and ensure that it covers enough of the features described for our localization support. At a high level this means that:
- The implementation supports changing the visible language of the UI
- The implementation supports multiple languages
- There's some way to add to or customize the translations that we provide
- There is a list of frontend plugins and core app frontend components identified that fully support localized strings

Out of scope is:
- Language directionality, the initial implementation will focus on enabling right-to-left languages.
- Message strings that are passed along from the backend to the UI, for example the error response from making a backend API call.

## Acceptance criteria

- [ ] tdb

## Requirements

- [ ] Test plan
- [ ] Documentation

## Issues in Epic

- [x] https://github.com/janus-idp/backstage-showcase/issues/557
- [x] https://github.com/janus-idp/backstage-showcase/issues/558
- [x] https://github.com/janus-idp/backstage-showcase/issues/559
- [x] https://github.com/janus-idp/backstage-showcase/issues/560
- [x] https://github.com/janus-idp/backstage-showcase/issues/561
- [x] https://github.com/janus-idp/backstage-showcase/issues/562
- [x] https://github.com/janus-idp/backstage-showcase/issues/563
- [x] https://github.com/janus-idp/backstage-showcase/issues/595
- [x] https://github.com/janus-idp/backstage-showcase/issues/596
- [ ] https://github.com/janus-idp/backstage-plugins/issues/903
- [x] https://github.com/janus-idp/backstage-plugins/issues/904
- [x] https://github.com/janus-idp/backstage-plugins/issues/905

## Notes

**Additional context**
Add any other context or screenshots about the epic here.

**Comment by rtaniwa** [comment]
Opening this as a placeholder epic for the work we will need to do around localization/internationalization. First story will require a spike on the [upstream i18n feature.](https://github.com/backstage/backstage/issues/4454)

**Comment by invincibleJai** [comment]
@jerolimov FYI,  feel free to assign this to yourself.
