### ISSUE TITLE
RBAC Enhancements 

### ISSUE THREAD

**Issue by kadel** [janus-idp/backstage-showcase#585]
**No-Code Authorization Authoring**: The plugin will offer an intuitive, no-code UI for defining and managing permissions and policies within backstage.io. Users can easily create and modify authorization rules without complex coding or configuration.

**Audit Logging**: The plugin will provide audit logging capabilities, recording all permission-related activities and changes made within the Backstage instance.

**Roles**: Remove the ability to assign users and groups directly to permission policies

**Caching and Performance**: Enhance the efficiency of the RBAC using caching and other methods.

**Conditional Policies**: Improvements to the conditional policy implementation. Add validation for conditional policies. Add aliases for some conditional policy parameters. Add the ability to load conditional policies using a file.

- [x] https://github.com/janus-idp/backstage-showcase/issues/363
- [x] https://github.com/janus-idp/backstage-showcase/issues/362
- [x] https://github.com/janus-idp/backstage-showcase/issues/605
- [x] https://github.com/janus-idp/backstage-showcase/issues/604
- [x] https://github.com/janus-idp/backstage-showcase/issues/623
- [x] https://github.com/janus-idp/backstage-plugins/issues/898
- [x] https://github.com/janus-idp/backstage-showcase/issues/606
- [x] https://github.com/janus-idp/backstage-showcase/issues/675
- [x] https://github.com/janus-idp/backstage-showcase/issues/671
- [x] https://github.com/janus-idp/backstage-plugins/issues/996
- [x] https://github.com/janus-idp/backstage-plugins/issues/900
- [x] https://github.com/janus-idp/backstage-plugins/issues/944

**Comment by PatAKnight** [comment]
Moving to close as all of the relevant issues have been closed or are being tracked through Jira.
