### ISSUE TITLE
Deploying  RHDH intance for dogfooding with starting configuration

### ISSUE THREAD

**Issue by kadel** [janus-idp/backstage-showcase#653]
We want to have our own RHDH instance that our team will use daily to manage Janus and RHDH development.

Acceptance criteria:
- [ ] Separate RHDH instance that is running nightly RHDH builds.
  - [ ] It is automatically updated every day 9pm Eastern time.
- [ ] GitHub integration is configured (using GitHub App)
  - [ ] GitHub Org Entity provider is enabled and configured to pull organization data from janus-idp
- [ ] GitHub Auth is configured
  - [ ] No guest access
  - [ ] Access is allowed only to GitHub users from predefined list (list of users will be provided later)
- [ ] Software catalog has records for all repos in janus-idp github org

**Comment by PatAKnight** [comment]
Blocked by #602. When this gets merged we will be able to remove guest access.
Will need to include `catalog-info.yaml` in all of the [repos](https://github.com/janus-idp/backstage-plugins/blob/main/catalog-info.yaml) that we wish to have in the software catalog.

**Comment by kadel** [comment]
replaced by https://issues.redhat.com/browse/RHIDP-727
