### ISSUE TITLE
Operator based on the Operator SDK

### ISSUE THREAD

**Issue by jasperchui** [janus-idp/backstage-showcase#680]
## Goal

This epic aims to provide an operator based on Operator SDK that is releaseable and usable state where it offers a comparable stable experience as installing via helm chart.

## Acceptance criteria

- [ ] Operator is able to deploy Backstage
- [ ] Operator can reconcile changes
- [ ] Operator can enforce Janus IDP image
- [ ] Operator can enforce proper routing

## Requirements

- [ ] Test plan
- [ ] Documentation

## Issues in Epic

- [ ] tbd

## Notes

**Additional context**
Add any other context or screenshots about the epic here.

**Comment by kadel** [comment]
> * [ ]  Operator is able to deploy Backstage

Should operator also handle PostgreSQL instance? Or the assumption is that users will use separate PostgreSQL operator?

> * [ ]  Operator can reconcile changes

How is Backstage configuration going to be stored? 
Doe the full `app-config.yaml` config going to be represented as CR or users will manage configuration in a separate ConfigMap?

> * [ ]  Operator can enforce Janus IDP image

what does it mean enforce IDP Image?

> * [ ]  Operator can enforce proper routing

What does it mean enforce proper routing?
